---
- name: Configure TLS Certificate Attributes
  community.general.ldap_attrs:
    dn: cn=config
    bind_dn: "cn=admin,cn=config"
    bind_pw: "{{ ldap_root_passwd }}"
    attributes:
      olcTLSCACertificateFile: "{{ slapd_ca_path }}/{{ ca_certificate_file }}"
      olcTLSCertificateFile: "{{ sldapd_tls_cert }}"
      olcTLSCertificateKeyFile: "{{ sldapd_tls_key }}"
    state: exact
  notify: restart slapd


- name: Enforce TLS for LDAP 389 Port
  when: slapd_enforce_tls
  community.general.ldap_attrs:
    dn: '{{ slapd_olcDatabase_type_dn }}'
    bind_dn: "cn=admin,cn=config"
    bind_pw: "{{ ldap_root_passwd }}"
    attributes:
      olcSecurity: tls=1
    state: exact
  notify: restart slapd

- name: Modify slapd configuration
  ansible.builtin.lineinfile:
    path: "{{ slapd_sysconfig_file }}"
    regex: '^SLAPD_SERVICES='
    line: 'SLAPD_SERVICES="ldap:/// ldapi:/// ldaps:///"'
  notify: restart slapd
