---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - ${MOLECULE_DISTRO:-ubuntu2204}
provisioner:
  name: ansible
  options:
    diff: true
  inventory:
    group_vars:
      all:
        slapd_cache_vaild_time: 0

        slapd_install_schema_cosine: false
        slapd_install_schema_nis: false
        slapd_install_schema_misc: false
        slapd_install_schema_ssh_lpk: false
        slapd_install_schema_sudo: false
        slapd_install_schema_samba3: false
        slapd_install_schema_custom: true
        slapd_schema_custom: "myschema"
        slapd_schema_custom_attributetypes:
          - "(  2.25.896523589646542388.3
                NAME 'authenticationUsername'
                SUP description
                EQUALITY caseExactMatch
                SYNTAX 1.3.6.1.4.1.1466.115.121.1.44
                SINGLE-VALUE )"
          - "(  2.25.896523589646542388.2
                NAME 'authenticationToken'
                SUP description
                EQUALITY caseExactMatch
                SYNTAX 1.3.6.1.4.1.1466.115.121.1.44
                SINGLE-VALUE )"
        slapd_schema_custom_objectclasses:
          - "(  2.25.896523589646542388.10
                NAME 'myauthenticationobject'
                STRUCTURAL
                SUP top
                MUST ( cn $$ authenticationUsername )
                MAY ( authenticationToken ) )"

        slapd_install_module_refint: false
        slapd_install_module_memberof: false
        slapd_install_module_syncprov: false

        slapd_replication: false

      # https://github.com/ktooi/ansible-role-slapd/issues/12
      rockylinux9:
        slapd_install_module_refint: false
        slapd_install_module_memberof: false
        slapd_install_module_syncprov: false
        slapd_replication: false
      rockylinux8:
        slapd_install_module_refint: false
        slapd_install_module_memberof: false
        slapd_install_module_syncprov: false
        slapd_replication: false
      centos7:
        slapd_install_module_refint: false
        slapd_install_module_memberof: false
        slapd_install_module_syncprov: false
        slapd_replication: false

verifier:
  name: ansible
